### ISSUE TITLE
European ash organism

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#151] opened 2018-02-05 20:17 UTC
European ash 
- [x] genome doesn’t link to downloads or browse - In general, need consistency of genome pages need to have downloads and a jbrowse link on all (how to enforce?)
- [x] no jbrowse on organism pane either
- [x] library link shows up even though there are no libraries

**Comment by almasaeed2010** [comment] 2018-02-05 21:12
I added the jbrowse link to European ash genome analysis page:  http://160.36.205.61:8095/Genome-assembly/1963052

I have no idea where the downloads are.

**Comment by bradfordcondon** [comment] 2018-02-05 21:32
>(how to enforce?)

as long as this is done via html, it will be a problem.

>I have no idea where the downloads are.

We don't host the downloads ourselves.  I added another link (which is a duplicate of the methods link) that says you can download the data there.

**Closed by bradfordcondon** 2018-02-05 21:32 UTC
Labels: Release Blocker
