### ISSUE TITLE
GO browser for Chinese chestnut v3.2 not working

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#525] opened 2019-06-04 12:43 UTC
### Bug description
No genes are available linked to GO terms when version 3.2 is selected.

<img width="724" alt="Screen Shot 2019-06-04 at 8 42 16 AM" src="https://user-images.githubusercontent.com/508122/58879927-c20e8200-86a4-11e9-9ece-c24274971c48.png">

Works fine for v1.1.
<img width="514" alt="Screen Shot 2019-06-04 at 8 42 33 AM" src="https://user-images.githubusercontent.com/508122/58879937-c5097280-86a4-11e9-8823-7d62722d33b6.png">

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment] 2019-06-04 12:43
Most likely just needs reindexing. I'll rerun the indexer.

**Comment by almasaeed2010** [comment] 2019-06-04 15:07
Reindexing finished but it's still not showing up.

**Comment by almasaeed2010** [comment] 2019-06-04 15:22
Running the following query suggests that there are no GO terms associated with any of the features that are associated with this analysis. 

```sql
select f.name, c.name, d.name from chado.feature f
inner join chado.feature_cvterm fc on fc.feature_id = f.feature_id
inner join chado.cvterm c on fc.cvterm_id = c.cvterm_id
inner join chado.analysisfeature af on af.feature_id = f.feature_id
inner join chado.dbxref x on x.dbxref_id = c.dbxref_id 
inner join chado.db d on d.db_id = x.db_id 
  where af.analysis_id = 282 and d.db_id in (109);
```

Moreover, visiting mRNA pages also do not display any annotations. So, it looks like GO has not been loaded for these features.

If you try the KEGG ontology browser, it works as intended when you attempt switching between analyses since the organism has KEGG loaded.

**Comment by mestato** [comment] 2019-06-19 18:45
@cricha59 do you remember loading these?

**Comment by CaseyRichards92** [comment] 2019-06-19 21:40
@mestato I do remember loading IPS but to be honest I could have skipped over the check box to load the GO terms. Would you like me to re-run IPS w/ the GO terms?

**Comment by CaseyRichards92** [comment] 2019-06-20 15:10
IPS CHADO LOADER re-ran with GO terms.
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/787565

**Comment by almasaeed2010** [comment] 2019-06-20 15:30
New job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/787569

**Comment by almasaeed2010** [comment] 2019-06-20 15:47
New annotations are showing up https://www.hardwoodgenomics.org/feature/Cm_g24542.t2?tripal_pane=gp_sio__annotation14713

I'll run the indexer for the browser

**Comment by almasaeed2010** [comment] 2019-06-20 19:17
@cricha59 @mestato this has been fixed. Feel free to test and close the issue.

Thanks!

**Closed as completed** 2019-06-25 15:04 UTC
Labels: bug :beetle:
